### PR TITLE
MAINT : added lint workflow test

### PR DESCRIPTION
**Pull request by Schefflera-Arboricola**
added `lint.yml`

### CODE REVIEW

**Review by dschult — APPROVED** [review]
This looks like it works. Did the linting tell us to change `type` to `isinstance` and to shorten the line in the doc_string?  Or are those changes we need for other reasons?

I approve this PR no matter what the answers to those questions are. :)

**Comment by Schefflera-Arboricola** [comment]
>  Did the linting tell us to change type to isinstance and to shorten the line in the doc_string?

yes

Also, should I add some more tests to this pr?

Thanks!

**Comment by dschult** [comment]
If the additional tests are linting related add them here -- otherwise it also makes sense to add them separately. That way it is easier to review the PRs.

**Comment by Schefflera-Arboricola** [comment]
I think we can add more in future.

**Pull request merged**
