### PR TITLE
MAINT: Added LICENSE and updated README

### PR DESCRIPTION
**Pull request by Schefflera-Arboricola**
As suggested by @rossbar in the last nx-community meeting I've added the installation instructions in the readme. I updated the readme with a few other changes as well. I also added the `CC0 1.0 Universal` license. LMK know what you think of that. Also, I tried following through the instructions in `RELEASE.md` but I couldn’t bcoz I don’t have the GH_TOKEN 
```
RuntimeError: You need to set the environment variable `GH_TOKEN`. The token is used to avoid rate limiting, and can be created at https://github.com/settings/tokens.
```

And I decided to remove the link to the _dispatchable decorator's docs because it will probably be moved around in the future and instead put the backend doc's page's link.

Thank you :)

### CODE REVIEW

**Comment by jarrodmillman** [comment]
Why not use a BSD-3 license?

**Comment by Schefflera-Arboricola** [comment]
> Why not use a BSD-3 license?

I'm not an expert in this but I choose to go with `CC0 1.0 Universal` license because I know that it has the least restrictions, also [nx-guides](https://github.com/networkx/nx-guides) use it so I thought maybe projects other than the main networkx project(in networkx org) use this license. Let me know if the BSD-3 or BSD-3-Clause or any other license would be more appropriate for this project and I'll change it. thanks!

**Comment by rossbar** [comment]
FWIW the reason nx-guides uses a CC license instead because the majority of the content is narrative text instead of code. I think BSD-3 is more appropriate here - just my 2 cents!

**Comment by dschult** [comment]
That is my understanding as well -- that CC is better for prose/text while BSD is better for code.
So, let's match the NetworkX license rather than the nx-guides license. :)

**Review by jarrodmillman — APPROVED** [review]

**Review by dschult — APPROVED** [review]
Looks good oto me!

**Pull request merged**
